version: '3'
networks:
  db:

services:
  database:
    image: mongo:3.6
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongo_password
    ports:
      - '27017-270129:27017-27019'
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./data:/data/db
  admin-app:
    dockerfile: ./parking-admin-app/Dockerfile
    container_name: parking-admin-app
    working_dir: /app
    ports:
      - '3000:3000'
    volumes:
      - ./parking-admin-app:/app
      - /app/node_modules
  events-app:
    dockerfile: ./parking-events-app/Dockerfile
    container_name: parking-events-app
    working_dir: /app
    volumes:
      - ./parking-events-app:/app
      - /app/vendor
      ports:
        - '8080:8080'
